# Loading Data

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv("winequality-white.csv", delimiter = ";")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


In [4]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

In [5]:
x = df.iloc[:,0:-1]
x.insert(0,'Ones',1)
x.head()

Ones  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     1            7.0              0.27         0.36            20.7   
1     1            6.3              0.30         0.34             1.6   
2     1            8.1              0.28         0.40             6.9   
3     1            7.2              0.23         0.32             8.5   
4     1            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  
0       0.45      8.8  
1       0.49      9.5  
2       0.44     10.1  
3       0.40      9.9  
4       0.40      9.9

In [6]:
y = df.iloc[:,-1]
y.head()

0    6
1    6
2    6
3    6
4    6
Name: quality, dtype: int64

In [7]:
y.unique()

array([6, 5, 7, 8, 4, 3, 9], dtype=int64)

In [8]:
y.describe()

count    4898.000000
mean        5.877909
std         0.885639
min         3.000000
25%         5.000000
50%         6.000000
75%         6.000000
max         9.000000
Name: quality, dtype: float64

In [9]:
theta = np.array([0.5]*len(x.columns))
theta

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

# Feature Scaling

In [10]:
for i in range(0,len(x.columns)):
    x.iloc[:,i] = x.iloc[:,i]/np.max(x.iloc[:,i])

x.head()

Ones  fixed acidity  volatile acidity  citric acid  residual sugar  \
0   1.0       0.492958          0.245455     0.216867        0.314590   
1   1.0       0.443662          0.272727     0.204819        0.024316   
2   1.0       0.570423          0.254545     0.240964        0.104863   
3   1.0       0.507042          0.209091     0.192771        0.129179   
4   1.0       0.507042          0.209091     0.192771        0.129179   

   chlorides  free sulfur dioxide  total sulfur dioxide   density        pH  \
0   0.130058             0.155709              0.386364  0.963445  0.785340   
1   0.141618             0.048443              0.300000  0.956708  0.863874   
2   0.144509             0.103806              0.220455  0.957766  0.853403   
3   0.167630             0.162630              0.422727  0.958248  0.835079   
4   0.167630             0.162630              0.422727  0.958248  0.835079   

   sulphates   alcohol  
0   0.416667  0.619718  
1   0.453704  0.669014  
2   0.407407  0.711268  
3   0.370370  0.697183  
4   0.370370  0.697183

# Linear Regression Model

In [11]:
# HYPOTHESIS FUNCTION
def hypothesis(theta,x):
    return x*theta

# COST FUNCTION
def computeCost(x,y,theta):
    #def computeCost(x,y,theta):
    y1 = hypothesis(theta,x)
    y1 = np.sum(y1,axis=1)
#     z = np.sum((y1-y)**2)/(2*len(x))
    return np.sum((y1-y)**2)/(2*len(x))

# GRADIENT DESCENT FUNCTION
def gradientDescent(x, y, theta, alpha, iters):
    J = [] # cost function
    for i in range(iters):
        y1 = hypothesis(theta,x)
        y1 = np.sum(y1, axis=1)
        for j in range(0,len(x.columns)):
            theta[j] = theta[j] - (alpha*(np.sum((y1-y)*x.iloc[:,j])))/len(x)
#             print(theta)
        cost = computeCost(x, y, theta) #cost
        J.append(cost)
    return J, theta

In [12]:
def predict(x, y, theta, alpha, iters):
    J, theta = gradientDescent(x, y, theta, alpha, iters) 
    H = hypothesis(theta, x)
    H = np.sum(H,axis=1)
    
    for i in range(0,len(H)):
        if H[i]>0 and H[i]<1:
            H[i]=0
        elif H[i]>1 and H[i]<2:
            H[i]=1
        elif H[i]>2 and H[i]<3:
            H[i]=2
        elif H[i]>3 and H[i]<4:
            H[i]=3
        elif H[i]>4 and H[i]<5:
            H[i]=4
        elif H[i]>5 and H[i]<6:
            H[i]=5
        elif H[i]>6 and H[i]<7:
            H[i]=6
        elif H[i]>7 and H[i]<8:
            H[i]=7
        elif H[i]>8 and H[i]<9:
            H[i]=8
        elif H[i]>9 and H[i]<10:
            H[i]=9
        else:
            H[i]=10
        
    return H, theta, J

In [41]:
theta = np.array([0.5]*len(x.columns))
alpha = 0.5
iters = 8000

H, theta, J = predict(x, y, theta, alpha, iters)

In [42]:
H

0       5.0
1       5.0
2       5.0
3       5.0
4       5.0
       ... 
4893    6.0
4894    5.0
4895    5.0
4896    6.0
4897    6.0
Length: 4898, dtype: float64

In [43]:
theta

array([ 1.17484823, -0.70869671, -2.15366985, -0.0483627 ,  1.67147687,
       -0.32604295,  1.38301032, -0.38563702,  0.8941505 ,  0.65282901,
        0.45116149,  5.16955854])

Cost function graph:

In [44]:
# Plotting the cost of each iteration to see the behavior
plt.figure(figsize=(15,15))
# plt.plot(J)
plt.scatter(x=list(range(0, 8000)), y=J)
plt.show()

# Output & Accuracy
The output is the variable 'Quality'. It has a score between 0 and 10. The wine is either “good quality” (a score of 7 or higher) or not (a score below 7).

In [45]:
acc = sum(y[k] == H[k] for k in range(0,len(y)))/len(y)
acc = acc*100
print(f'ACCURACY = {acc:.2f} %')

ACCURACY = 44.90 %


In [46]:
H

0       5.0
1       5.0
2       5.0
3       5.0
4       5.0
       ... 
4893    6.0
4894    5.0
4895    5.0
4896    6.0
4897    6.0
Length: 4898, dtype: float64

In [47]:
H.describe()

count    4898.000000
mean        5.375664
std         0.539019
min         3.000000
25%         5.000000
50%         5.000000
75%         6.000000
max         7.000000
dtype: float64